dist: trusty
sudo: false

language: generic

notifications:
  email: false

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran

install:
  - pyenv global 2.7.13
  - pip install -U pip setuptools
  - pip install -r requirements.txt

script:
  - travis_wait 60 pytest -vv tests
